Repository Shreyas6973/List-of-Programing-Language, pull requests merged in 2022-09, with the labels that each got.

#2 New Laguage Added
  Language _ List.json
Labels: hactoberfeast, hacktoberfest

#4 Added new language - Java
  Language _ List.json
Labels: hacktoberfest

#7 Update Language _ List.json
  Language _ List.json
Labels: hactoberfeast, hacktoberfest, hacktoberfest-accepted

#8 Update Language _ List.json
  Language _ List.json
Labels: hactoberfeast, hacktoberfest, hacktoberfest-accepted
